"""test  migrate

Revision ID: 75a3381de0a0
Revises: ab6ac25f7776
Create Date: 2022-11-04 22:15:00.501815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a3381de0a0'
down_revision = 'ab6ac25f7776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounthistory', sa.Column('label', sa.Enum('STANDARD', 'PRIVILEGED', 'ADMIN', 'TEST', name='roletype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounthistory', 'label')
    # ### end Alembic commands ###
